### ISSUE TITLE
关于 thinkjs 这个名字的使用问题

### ISSUE THREAD

**Issue by welefen** [thinkjs/autocommand-cli#1]
hi，你好

冒昧的在这里打扰你了，在你博客上留言没见回复。
是这样的，我是 360 奇舞团的工程师，我们团队开源了一款 Node.js 框架，名字叫做 ThinkJS，所以想在 GitHub 上用 thinkjs 这个名称（https://github.com/thinkjs）。但发现这个名字在 2010 年已经被你使用了，所以冒昧的问下是否愿意将这个名字转给我们（我们可以提供一定的报酬）。
我的 QQ 是：499979038，微信是： welefen

如果对你有打扰，请关闭该 issue，多谢了。

**Comment by lccf** [comment]
已加微信
